---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure LXC
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  categories:
    - development
    - system
dependencies: []
