---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure Vagrant
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
    - name: Ubuntu
      versions:
        - zesty
  categories:
    - development
    - system
dependencies:
  - { role: virtualbox, tags: virtualbox }
