---
- name: Install Required Packages | Homebrew
  homebrew_cask: name={{ item  }} state=present
  with_items:
    - virtualbox
    - virtualbox-extension-pack
  when: ansible_distribution == 'MacOSX'

- name: Install Required Packages | Packages
  package: name={{ item }} state=latest
  become: yes
  with_items: '{{ virtualbox_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution != 'MacOSX'
